services:
  nestjs:
    container_name: nestjs-todokkabi
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    ports:
      - "3000:3000"

    command: npm run start:dev
    depends_on:
      mysql-project:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/app/src
      - ./libs:/usr/src/app/libs
    env_file:
      - .env.development

  mysql-project:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: projectdb
      MYSQL_USER: "project"
      MYSQL_PASSWORD: "1234"
      MYSQL_ROOT_PASSWORD: "1234"
    ports:
      - "6003:3306"
    volumes:
      - "mysql_nest_data:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: redis-todokkabi
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    command: redis-server --appendonly yes

volumes:
  mysql_nest_data:
  redis_data:
